### ISSUE TITLE
ch06: Installation of virtualenvwrapper fails

### ISSUE THREAD

**Issue by nmusatti** [lorin/ansiblebook#15]
The mezzanine.yml palybook fails when executing the "install Python requirements globally via pip" task for virtualenvwrapper with the following error message:

failed: [web] (item=virtualenvwrapper) => {"changed": false, "cmd": "/usr/local/bin/pip2 install -U virtualenvwrapper", "item": "virtualenvwrapper", "msg": "stdout: Collecting virtualenvwrapper\n  Downloading https://files.pythonhosted.org/packages/2b/8c/3192e10913ad945c0f0fcb17e9b2679434a28ad58ee31ce0104cba3b1154/virtualenvwrapper-4.8.2-py2.py3-none-any.whl\nCollecting virtualenv-clone (from virtualenvwrapper)\n  Downloading https://files.pythonhosted.org/packages/6d/c2/dccb5ccf599e0c5d1eea6acbd058af7a71384f9740179db67a9182a24798/virtualenv_clone-0.3.0-py2.py3-none-any.whl\nCollecting stevedore (from virtualenvwrapper)\n  Downloading https://files.pythonhosted.org/packages/17/6b/3b7d6d08b2ab3e5ef09e01c9f7b3b590ee135f289bb94553419e40922c25/stevedore-1.28.0-py2.py3-none-any.whl\nRequirement not upgraded as not directly required: virtualenv in /usr/local/lib/python2.7/dist-packages (from virtualenvwrapper) (15.2.0)\nCollecting six>=1.10.0 (from stevedore->virtualenvwrapper)\n  Downloading https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl\nCollecting pbr!=2.1.0,>=2.0.0 (from stevedore->virtualenvwrapper)\n  Downloading https://files.pythonhosted.org/packages/e1/ba/f95e3ec83f93919b1437028e989cf3fa5ff4f5cae4a1f62255f71deddb5b/pbr-4.0.2-py2.py3-none-any.whl (98kB)\nInstalling collected packages: virtualenv-clone, six, pbr, stevedore, virtualenvwrapper\n  Found existing installation: six 1.5.2\n\n:stderr: /usr/local/lib/python2.7/dist-packages/pip/_vendor/urllib3/util/ssl_.py:339: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  SNIMissingWarning\n/usr/local/lib/python2.7/dist-packages/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecurePlatformWarning\n/usr/local/lib/python2.7/dist-packages/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecurePlatformWarning\ncheetah 2.4.4 requires Markdown>=2.0.1, which is not installed.\nlaunchpadlib 1.10.2 requires testresources, which is not installed.\nCannot uninstall 'six'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.\n"}

**Comment by nmusatti** [comment]
I opened this issue here because I couldn't find a way to open it in the ansiblebook/ansiblebook repository.

**Comment by jethigh** [comment]
Hi.

Try to install virtualenvwrapper with apt and comment in where it's installed with pip.

```
    - name: install apt packages
      apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
      become: True
      with_items:
        - git
        - libjpeg-dev
        - memcached
        - nginx
        - postgresql
        - python-dev
        - python-pip
        - python-psycopg2
        - python-setuptools
        - python-virtualenv
        - supervisor
        - virtualenvwrapper
```

 ```
   - name: install Python requirements globally via pip
      pip: name={{ item }} state=latest
      with_items:
        - pip
        - virtualenv
# Installed as system package
#        - virtualenvwrapper
```
